# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roots', '0002_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/image.jpeg', upload_to='/images')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('pseudo', models.CharField(max_length=30)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='post',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='portraits',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='roots.Portraits'),
        ),
        migrations.AddField(
            model_name='portraits',
            name='photo',
            field=models.ImageField(default='images/image.jpeg', upload_to='/images'),
        ),
    ]
