# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0004_auto_20160201_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='portraits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='roots.Portraits'),
        ),
    ]
